name: ci-two-spaceships

on:
#  push:
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORK_DIR: TwoSpaceships

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-node-project
        with:
          working-directory: ${{ env.WORK_DIR }}

      - name: Run npm audit
        id: audit
        continue-on-error: true
        uses: ./.github/actions/npm-audit-summary



      - name: Generate HTML report
        working-directory: ${{ env.WORK_DIR }}
        run: npm audit --json | npx audit-export

      - name: Upload Audit HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twospaceships-npm-audit-report
          path: ${{ env.WORK_DIR }}/audit-report.html
          retention-days: 7

      - name: Fail job if audit failed
        if: steps.audit.outcome == 'failure'
        run: exit 1
