name: "[SI] CI"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore: [main]
    paths:
      - 'SpaceInvaders/**'
      - '.github/workflows/ci-space-invaders.yml'
      - '.github/workflows/_ci-game.yml'
      - '.github/actions/**'
  pull_request:
    branches: [main]
    paths:
      - 'SpaceInvaders/**'
      - '.github/workflows/ci-space-invaders.yml'
      - '.github/workflows/_ci-game.yml'
      - '.github/actions/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: "CI Suite"
    uses: ./.github/workflows/_ci-game.yml
    with:
      game-name: SpaceInvaders
      work-dir: SpaceInvaders
      artifact-prefix: spaceinvaders
    secrets: inherit
