# .github/workflows/ci-two-spaceships.yml
name: ci-two-spaceships

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WorkDir: TwoSpaceships

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-project
        with:
          working-directory: ${{ env.WorkDir }}

      - name: Run ESLint
        working-directory: ${{ env.WorkDir }}
        run: npm run lint

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-project
        with:
          working-directory: ${{ env.WorkDir }}

      - name: Run tests
        working-directory: ${{ env.WorkDir }}
        run: npm run test && npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        id: upload-report
        with:
          name: vitest-report
          path: ${{ env.WorkDir }}/html/
          retention-days: 7

  e2e:
    name: Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-project
        with:
          working-directory: ${{ env.WorkDir }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ${{ env.WorkDir }}/playwright-report/
          retention-days: 7
